### ISSUE TITLE
NPM install fails

### ISSUE THREAD

**Issue by alexcroox** [gruppe-adler/arma3-serverinfo#2]
``````
39 error Exit status 1
40 error Failed at the arma3-serverstats@1.0.0 install script './node_modules/tsd/build/cli.js reinstall --save --override; node_modules/typescript/bin/tsc --module commonjs  ./*.ts */*.ts'.
40 error This is most likely a problem with the arma3-serverstats package,
40 error not with npm itself.
40 error Tell the author that this fails on your system:
40 error     ./node_modules/tsd/build/cli.js reinstall --save --override; node_modules/typescript/bin/tsc --module commonjs  ./*.ts */*.ts```
``````

**Comment by Dahlgren** [comment]
This is most probably related to #1. It should be possible to start the application with `node main.js` anyway, otherwise you can remove line 194 and 195 from lib/webserver.ts and run `npm install` again. These are the troublesome lines

``` js
    else
        return res.send(new restify.MethodNotAllowedError());
```

**Comment by Fusselwurm** [comment]
@Dahlgren @alexcroox it seems the guys at DefinitelyTyped are taking their time with https://github.com/borisyankov/DefinitelyTyped/pull/4015 , so fixed it on our side.

**Comment by alexcroox** [comment]
Excuse my ignorance, I've made several node applications before but I've never used this .ts structure before. How do I start the application? `node main.ts` errors out and `node main.js` as per your instructions above fails because main.js doesn't exist. Is there a build step I'm missing?

**Comment by Fusselwurm** [comment]
@alexcroox It's Typescript, a Javascript derivative that knows strict typing - basically Microsoft's stab at Ecmascript 6. I'm using it because typed callbacks are the best thing that has happened to my productivity in a long time ;)

Anyhow - Typescript compiles to Javascript. 

The install script does that. Should do, that is. After `npm inst` , _there should be_ a main.js that you can start.

There's two steps here that I put into that package.json#scripts/install line:

First `./node_modules/tsd/build/cli.js reinstall --save --override`  installs the "typings", these are basically header files / interface declarations for many of the used js libraries, so the Typescript compiler knows what to expect, and how to warn me if I use things wrongly.

Secondly, `node_modules/typescript/bin/tsc --module commonjs ./*.ts */*.ts` compiles all Typescript files into their Javascript equivalents.

Unfortunately, the error message tells us nothing about at which step the problem lies.

Could you try to do the following on a clean checkout:
- remove the scripts/install line from package.json
- run `npm install` 
- then, run  `./node_modules/tsd/build/cli.js reinstall --save --override`
- if the former worked, run  `node_modules/typescript/bin/tsc --module commonjs ./*.ts */*.ts`

and tell me where it dies, and what the error output is?

**Comment by alexcroox** [comment]
I managed to get it installed with `tsc main.ts` just battling with getting Redis installed on Windows before I can continue (previously only ever installed on unix based systems).

**Comment by Dahlgren** [comment]
the `npm install` command is currently broken on Windows, see #3

**Comment by Fusselwurm** [comment]
If there's anything wrong with/on Windows, I wont be able to help you - but I'll appreciate any fixes you can come up with ;)

Btw, Visual Studio should have the best Typescript support you can find :)
